#!/bin/bash

function usage {
	echo ""
	echo "HiC2MFA_Mapper"
	echo ""
	echo "A program that uses the reads of a Hi-C to create a Depth of sequencing file to be analyzed as an MFA."
	echo "(It uses the data generated by hicstuff)"
	echo ""
	echo "OUTPUT"
	echo "A txt file containing the depth of sequencing for each nucleotide on the reference genome"
	echo ""
	echo "USAGE"
	echo ""
	echo "HiC2MFA_mapper -n [name of the experiment] -f [folder]"
	echo ""
	echo "-n|--name		name of the experiment"
	echo "					E.G. -n FO01. Will be used to:"
	echo "					- Locate the name.far.bam and name.rev.bam files on the temp folder (hicstuff output)"
	echo "					- Name all the files generated"
	echo "-f|folder		Location folder (generated by hicstuff)"
}

TEMP=`getopt -o n:f:h --long name:,folder:,help -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.

while true ; do
    case "$1" in
    	-h|--help)
			usage ; exit 0 ;;
        -f|--folder)
            folder=$2 ; shift 2 ;;
		-n|--name)
            name=$2 ; shift 2;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

#echo "name is : $name"
#echo "folder is : $folder"

outputFolder=${folder}/${name}
mkdir ${outputFolder}/HiC_2_MFA
touch ${outputFolder}/HiC_2_MFA/$name.HiC2MFA.log

samtools merge -@ 4 ${outputFolder}/HiC_2_MFA/${name}_HiC2MFA_merge.bam ${outputFolder}/tmp/${name}.for.bam ${outputFolder}/tmp/${name}.rev.bam

PicardCommandLine SortSam \
I=${outputFolder}/HiC_2_MFA/${name}_HiC2MFA_merge.bam  \
O=${outputFolder}/HiC_2_MFA/${name}_HiC2MFA_merge_sorted.bam \
SORT_ORDER=coordinate 2>> ${outputFolder}/HiC_2_MFA/$name.HiC2MFA.log

samtools depth -d 1000000 \
${outputFolder}/HiC_2_MFA/${name}_HiC2MFA_merge_sorted.bam   > ${outputFolder}/HiC_2_MFA/depth_${name}_HiC.txt